# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './MainWindow_suakii.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1232, 799)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.programControlGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.programControlGroup.setGeometry(QtCore.QRect(10, 10, 251, 161))
        self.programControlGroup.setObjectName("programControlGroup")
        self.connectButton = QtWidgets.QPushButton(self.programControlGroup)
        self.connectButton.setGeometry(QtCore.QRect(90, 110, 101, 31))
        self.connectButton.setObjectName("connectButton")
        self.refreshButton = QtWidgets.QPushButton(self.programControlGroup)
        self.refreshButton.setGeometry(QtCore.QRect(10, 110, 81, 31))
        self.refreshButton.setObjectName("refreshButton")
        self.layoutWidget = QtWidgets.QWidget(self.programControlGroup)
        self.layoutWidget.setGeometry(QtCore.QRect(90, 40, 104, 56))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comPortDropdown = QtWidgets.QComboBox(self.layoutWidget)
        self.comPortDropdown.setEnabled(True)
        self.comPortDropdown.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comPortDropdown.setObjectName("comPortDropdown")
        self.verticalLayout.addWidget(self.comPortDropdown)
        self.baudRateDropdown = QtWidgets.QComboBox(self.layoutWidget)
        self.baudRateDropdown.setObjectName("baudRateDropdown")
        self.verticalLayout.addWidget(self.baudRateDropdown)
        self.layoutWidget1 = QtWidgets.QWidget(self.programControlGroup)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 40, 79, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comPortLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.comPortLabel.setObjectName("comPortLabel")
        self.verticalLayout_2.addWidget(self.comPortLabel)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.graphicsView = GraphicsLayoutWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(270, 30, 951, 731))
        self.graphicsView.setObjectName("graphicsView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GSHSAT (suakii@gmail.com) [2022]"))
        self.programControlGroup.setTitle(_translate("MainWindow", "Port Control"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.refreshButton.setText(_translate("MainWindow", "Refresh"))
        self.comPortLabel.setText(_translate("MainWindow", "COM Port:"))
        self.label_3.setText(_translate("MainWindow", "BAUD RATE:"))
from pyqtgraph import GraphicsLayoutWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
